import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "@/lib/react-toastify/toast-provider";

export const metadata: Metadata = {
  title: "PollParty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
